### ISSUE TITLE
Work distribution

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-pieceofcake#12]
Please find a way to distribute your work more equally. 
While the UML diagrams are really useful, they should not be the major contribution of one of your team members. Think about automating them and split the other tasks in a more balanced way.

**Comment by SogolHaghighat** [comment]
@argenos we will. thank you. Please be aware that we do pair programming and discuss every step as well.

**Comment by argenos** [comment]
@SogolHaghighat you can still divide the workload equally. If you’re pair programming, you should be taking turns; whoever is responsible for that part of the code should be the one behind the keyboard.
