### ISSUE TITLE
Awesome! Sonar is running. Now fix critical warnings.

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-pieceofcake#6]
Good job on implementing the sonar connection. 👍 

Now fix all the critical warnings 😆... so consider it a head start.

The other groups will get the same task eventually too, correct @argenos?

**Comment by moriarty** [comment]
Great, I just saw this:

https://sonarcloud.io/project/issues?id=project-pieceofcake&issues=AV_l99Tw0ZS4AMhl2QqH&open=AV_l99Tw0ZS4AMhl2QqH

And this is awesome example of 2 things:
1. Sonar shows that the cognitive complexity here is too high, which basically means you need to re-factor it a bit. This is expected and in a general CS course, you'd just re-factor and be done...
2. But, this is a Multi-Agent Systems class, and we're using the JADE... So, instead of just breaking this up and refactoring the usual way, I would suggest digging around a little and seeing what tools and multi-agent paradigms are at your disposal to reduce the cognitive complexity measure.

**Comment by moriarty** [comment]
> The other groups will get the same task eventually too

Eventually has arrived.

**Comment by tmetzl** [comment]
Would this be a compliant solution using multi agent paradigms?

https://sonarcloud.io/code?id=project-pieceofcake%3AReduceComplexity-Feature&selected=project-pieceofcake%3AReduceComplexity-Feature%3Asrc%2Fmain%2Fjava%2Fmaas%2Fagents%2FCustomerAgent.java

**Comment by moriarty** [comment]
Yes that's what meant :+1: 

Here is a decent reference. https://www.iro.umontreal.ca/~vaucher/Agents/Jade/primer6.html
