### ISSUE TITLE
Sonar automated pull request analysis

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-pieceofcake#7]
https://docs.travis-ci.com/user/sonarcloud/#Activation-for-internal-pull-requests
https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

You've already setup sonar, I recommend you also enable the GitHub Plugin. This will automate much of the code review process.

**Comment by tmetzl** [comment]
I think this can be closed. Implemented the SonarQube GitHub Plugin in branch Development. You can see the checks working here:
https://github.com/HBRS-MAAS/project-pieceofcake/pull/8
